# Generated by Django 3.1.7 on 2021-10-13 12:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='PendingBlock',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('block', models.JSONField()),
                ('block_number', models.IntegerField()),
                ('block_hash', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['-block_number'],
                'unique_together': {('block_number', 'block_hash')},
            },
        ),
    ]
