name: Continuous integration

on:
  push:
    branches:
      - master

jobs:
# github does not support dependencies on other workflows therefore we have to duplicate the code
# QUALITY-ASSURANCE-START
  quality-assurance:
    name: Quality Assurance

    runs-on: ubuntu-latest
    container: python:3.9.2

    services:
      # TODO(dmu) LOW: This section duplicates services already defined in `docker-compose.yml`.
      #                Is there a way to make it DRY?
      db:
        image: postgres:13.2-alpine
        env:
          POSTGRES_DB: thenewboston_node
          POSTGRES_USER: thenewboston
          POSTGRES_PASSWORD: thenewboston
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Run Poetry image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4

      - name: Install
        run: make install && make install-pre-commit

      - name: Lint
        run: make lint

      - name: Test
        run: make test
        env:
          THENEWBOSTON_NODE_TEST_WITH_ENV_VARS: 'true'
          THENEWBOSTON_NODE_DATABASES: '{"default":{"HOST":"db"}}'
          THENEWBOSTON_NODE_SECRET_KEY: dummy
          THENEWBOSTON_NODE_NODE_SIGNING_KEY: 0000000000000000000000000000000000000000000000000000000000000000
# QUALITY-ASSURANCE-END

  publish-image:
    name: Publish docker images
    needs: quality-assurance
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push node image to Github Packages
        uses: docker/build-push-action@v2
        with:
          target: node
          tags: docker.pkg.github.com/thenewboston-developers/thenewboston-node/thenewboston-node:latest
          push: true
          # TODO(dmu) LOW: Make a better way of forcing the download of latest blockchain state
          no-cache: true
      - name: Push reverse-proxy image to Github Packages
        uses: docker/build-push-action@v2
        with:
          target: reverse-proxy
          tags: docker.pkg.github.com/thenewboston-developers/thenewboston-node/thenewboston-node-reverse-proxy:latest
          push: true
  deploy:
    name: Deploy to develoment environment
    needs: publish-image
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        # TODO(dmu) MEDIUM: Once/if github implements secrets on job level
        #                   https://github.com/actions/runner/issues/520#issuecomment-877193387
        if: ${{ env.NODE_CONTINUOUS_DEPLOYMENT_ENABLED == 'True' }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_SSH_KEY" > ~/.ssh/github
          chmod 600 ~/.ssh/github
          cat >>~/.ssh/config <<END
          Host target
            HostName $DEPLOY_SSH_HOST
            User $DEPLOY_SSH_USER
            IdentityFile ~/.ssh/github
            LogLevel ERROR
            StrictHostKeyChecking no
          END
        env:
          NODE_CONTINUOUS_DEPLOYMENT_ENABLED: ${{ secrets.NODE_CONTINUOUS_DEPLOYMENT_ENABLED }}
          DEPLOY_SSH_KEY: ${{ secrets.NODE_DEPLOY_SSH_KEY }}
          DEPLOY_SSH_HOST: ${{ secrets.NODE_DEPLOY_SSH_HOST }}
          DEPLOY_SSH_USER: ${{ secrets.NODE_DEPLOY_SSH_USER }}

      - name: Run deploy
        run: |
          ssh target "docker system prune --all --volumes --force && wget https://raw.githubusercontent.com/thenewboston-developers/thenewboston-node/master/scripts/deploy.sh -O /tmp/deploy-node.sh && chmod a+x /tmp/deploy-node.sh && /tmp/deploy-node.sh $GITHUB_ACTOR $GITHUB_PASSWORD True True && rm -f /tmp/deploy-node.sh"
        env:
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
